---
- name: Create lab namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ user.key }}-lab"

- name: Grant user admin access to lab namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: user-admin
        namespace: "{{ user.key }}-lab"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
        - kind: User
          apiGroup: rbac.authorization.k8s.io
          name: "{{ user.key }}"

- name: Grant showroom service account admin access to lab namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: showroom-admin
        namespace: "{{ user.key }}-lab"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
        - kind: ServiceAccount
          name: showroom
          namespace: "showroom-{{ guid }}-{{ user.key }}"
