---
- name: Prepare variables
  ansible.builtin.include_tasks: prepare_variables.yml

- name: Provision lab resources for each user
  ansible.builtin.include_tasks: user_lab_resources.yml
  loop: "{{ _workload_user_data.users | dict2items }}"
  loop_control:
    loop_var: user
    label: "{{ user.key }}-lab"
  when: _workload_user_data.users is defined
