---
- name: Create lab namespace for each user
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: >-
          {{ ocp4_workload_authentication_htpasswd_user_base }}{{ item }}-lab
  loop: >-
    {{ range(1, ocp4_workload_authentication_htpasswd_user_count | int + 1) | list }}
  loop_control:
    label: >-
      {{ ocp4_workload_authentication_htpasswd_user_base }}{{ item }}-lab
