apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-default-limits
  labels:
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
