apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-safety-quota
  labels:
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  hard:
    pods: "40"
    persistentvolumeclaims: "10"
