apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-2-3
  labels:
    app: lab-2-3-app
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
