apiVersion: v1
kind: Service
metadata:
  name: lab-4-4-backend-svc
  labels:
    app: lab-4-4-backend
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  selector:
    app: lab-4-4-backend
  ports:
  - port: 8080
    targetPort: 8080
