apiVersion: v1
kind: Service
metadata:
  name: lab-3-1-svc
  labels:
    app: lab-3-1-webapp
    demo.redhat.com/name: ocp-troubleshooting-workshop
spec:
  selector:
    app: lab-3-1-webapp
  ports:
  - port: 8080
    targetPort: 8080
